# local
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: medical_task_tracker_development

# test:
#   <<: *default
#   database: medical_task_tracker_test

# production:
#   <<: *default
#   database: medical_task_tracker_production
#   username: medical_task_tracker
#   password: <%= ENV["MEDICAL_TASK_TRACKER_DATABASE_PASSWORD"] %>

# docker
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: task_tracker_development

test:
  <<: *default
  database: task_tracker_test
